{
 "title": "Quest dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT lat, lon, decibels FROM candlestick_test ORDER BY timestamp LIMIT 1000;"
    }
   ]
  },
  {
   "title": "Devices Reporting",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT_DISTINCT(device_id) FROM candlestick_test;"
    }
   ]
  },
  {
   "title": "Readings during time window",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM candlestick_test;"
    }
   ]
  },
  {
   "title": "First three devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT decibels AS value, timestamp as time, CAST(device_id AS text) FROM candlestick_test WHERE device_id IN (1,2,3)"
    }
   ]
  }
 ]
}